### ISSUE TITLE
Remove Web3.js injection dependency [BOUNTY $100]

### ISSUE THREAD

**Issue by fulldecent** [su-squares/tenthousandsu.com#3]
Tenthousandsu.com currently relies on MetaMask's injected Web3.js dependency.

This approach is no longer recommended by MetaMask and is not compatible with Opera.

Apparently it is "simple" to do. But I can't find documentation of the canonical way to do iit.

# Requirements

- Makes the current tenthousandsu.com website work on Chrome+MetaMask AND iOS+Opera
- Loads Web3.js from a reliable CDN that many other people are using
- Does not change build process (we will not switch to npm for this)
- Minimizes impact on existing code

# References:

- https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8 (previously named *Breaking Change: No Longer Injecting Web3*)
- https://ethereum.stackexchange.com/questions/60904/where-is-the-latest-metamask-hello-world-dapp-example issue with bounty on SO
- https://explorer.bounties.network/bounty/2326 Bounty on The Bounties Network
- https://github.com/su-squares/tenthousandsu.com/pull/2 Work-in-progress PR

-----

other random notes

Make su squares work on Opera

Add these notes to the issue tracker 

WHAT DOES METAMASK USE?

web3.version.api

0.20.3

    git rev-parse v0.20.6
    cd1cfd9db6cacb494884a1824f8562c6440f85df
    git checkout cd1cfd9db6cacb494884a1824f8562c6440f85df
    

TWEET

Made minor updates to Su Squares white paper

BUILD WEB3JS

    git clone git@github.com:ethereum/web3.js.git
    cd web3.js
    git rev-parse v1.0.0-beta.55
    git checkout 3e4427940be4aa897d33c3ecb559d8cec9179e2b
    
    # FROM README
    npm install # install all dependencies for npm run bootstrap
    npm run bootstrap # install all dependencies and symlinks the internal modules for all modules
    npm run build # runs rollup
    npm run test # runs all tests 
    npm run clean # removes all the node_modules folders in all modules
    npm run dev # runs rollup with a watcher
    
    

ISSUES

https://github.com/ethereum/web3.js/issues/2729

https://github.com/ethereum/web3.js/issues/2623

https://github.com/ethereum/web3.js/issues/2013

https://github.com/ethereum/web3.js/issues/2839

https://www.reddit.com/r/ethereum/comments/44vd3f/exact_steps_to_connect_web3js_to_html_page_so_i/

https://explorer.bounties.network/bounty/2326

https://ethereum.stackexchange.com/questions/25651/what-is-the-metamask-workaround-if-web3-is-deprecated

---

https://raw.githubusercontent.com/ethereum/web3.js/v0.20.6/dist/web3.min.js

https://raw.githubusercontent.com/ethereum/web3.js/cd1cfd9db6cacb494884a1824f8562c6440f85df/dist/web3.min.js

curl ‘https://raw.githubusercontent.com/ethereum/web3.js/cd1cfd9db6cacb494884a1824f8562c6440f85df/dist/web3.min.js’ | openssl dgst -sha384 -binary | openssl base64 -A

rXHfd7f1o1jpr3t+dYI17CkzUY3Wswo1OGbiXPGSbg4s2E42+jkRgllwt7ss2Vlq

https://cdn.jsdelivr.net/gh/ethereum/web3.js@0.20.6/dist/web3.min.js

https://www.srihash.org

```
<script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js@0.20.6/dist/web3.min.js" integrity="sha384-rXHfd7f1o1jpr3t+dYI17CkzUY3Wswo1OGbiXPGSbg4s2E42+jkRgllwt7ss2Vlq" crossorigin="anonymous"></script>
```

**Comment by owocki** [comment]
we just did this over at gitcoin; heres a PR if you want to copy it => https://github.com/gitcoinco/web/pull/5432

**Comment by fulldecent** [comment]
Cool thank you, I'll check it out

**Comment by wbt** [comment]
Is this still Open?

**Comment by fulldecent** [comment]
Yes.

**Comment by wbt** [comment]
Is the bounty as well? It's marked 5 months expired.

**Comment by fulldecent** [comment]
Bounty is still active as is.

Not sure where you are seeing expired. But this issue here and my commitment to pay this bounty is active.
